import { Icons } from "../../../assets/icons";

export const SportButtonList = [
    {
        id: 1,
        title: "Nike Jordan N312",
    },
    {
        id: 2,
        title: "Adidas Predator",
    },
    {
        id: 3,
        title: "New Balance 240",
    },
    {
        id: 4,
        title: "FILA Super SPEED",
    },
    {
        id: 5,
        title: "Nike Jordan N312",
    },
];

export const SportMenuPeriod = [
    {
        id: 1,
        title: "Неважно",
    },
    {
        id: 2,
        title: "От 1 дней",
    },
    {
        id: 3,
        title: "От 5 дней",
    },
    {
        id: 4,
        title: "От 10 дней",
    },
];

export const SportMenuBrend = [
    {
        id: 1,
        title: "Adidas",
    },
    {
        id: 2,
        title: "Nike",
    },
    {
        id: 3,
        title: "New Balance",
    },
    {
        id: 4,
        title: "FILA",
    },
    {
        id: 5,
        title: "Jordan",
    },
];

export const SportMenuSize = [
    {
        id: 1,
        title: "30",
    },
    {
        id: 2,
        title: "31",
    },
    {
        id: 3,
        title: "32",
    },
    {
        id: 4,
        title: "33",
    },
    {
        id: 5,
        title: "34",
    },
];

export const SportList = [
    {
        id: 1,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 2,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 3,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 4,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 5,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 6,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 7,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 8,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 9,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 10,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 11,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 12,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 13,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 14,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 15,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 16,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 17,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 18,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 19,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
    {
        id: 20,
        title: "Yeezy Boost 350 V2 'Clay' Orange",
        img: "https://static.cdek.shopping/images/shopping/b8a8a78b34c245899548b8cf0b5ae396.jpg",
        text: "в наличии",
        icon: <Icons.trandIcon />,
        star: <Icons.trandStar />,
        whiteStar: <Icons.trandStarWhite />,
        priceForMonth: "1 567 000 сум ",
        Month: "в месяц",
        price: "15 999 000 сум",
        path: "/trainers",
    },
];
